# Generated by Django 4.1.3 on 2022-11-24 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksappOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2022, 11, 24, 19, 50, 3, 652141))),
                ('order_price', models.FloatField()),
            ],
            options={
                'db_table': 'orderdb',
            },
        ),
        migrations.CreateModel(
            name='BooksappRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'roledb',
            },
        ),
        migrations.AlterModelOptions(
            name='booksappbook',
            options={},
        ),
        migrations.CreateModel(
            name='BooksappUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
                ('user_login', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookcrud.booksapprole')),
            ],
            options={
                'db_table': 'userdb',
            },
        ),
        migrations.CreateModel(
            name='BooksappOrderBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookcrud.booksappbook')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookcrud.booksapporder')),
            ],
            options={
                'db_table': 'order_bookdb',
            },
        ),
        migrations.AddField(
            model_name='booksapporder',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookcrud.booksappuser'),
        ),
    ]
