# Generated by Django 4.1.3 on 2022-11-24 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrud', '0002_booksapporder_booksapprole_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksappuser',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booksappuser',
            old_name='user_login',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='booksappuser',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booksappuser',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='booksappuser',
            old_name='user_role',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='booksapporder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 21, 0, 0, 392039)),
        ),
    ]
